### ISSUE TITLE
Typha cannot be recovered when it loses the connection to kube-apiserver

### ISSUE THREAD

**Issue by kfyharukz** [projectcalico/typha#337]
## Expected Behavior

When typha lost the connection to the kube-apiserver, I expect that typha tries to recover automatically by retrying. Or, it should set liveness probe to false or exit the process to enable for k8s to operate typha Pod lifecycle.

I noticed the code had been written to retry to connect the kube-apiserver, but it didn't work.

## Current Behavior

When typha lost the connection to the kube-apiserver, typha does not retry (and does not set liveness probe to false or exit the process).

I think, because of the above typha behavior, calico-node could not access to typha, then calico-node could not become ready.

## Possible Solution

For a workaround, I deleted typha Pod manually (i.e. recreated the Pod). After that, typha worked correctly and calico-node could access typha.

I cannot make clear why typha process does not retry to connect the kube-apiserver. However, I think, when list/watch fails, typha should set liveness=false, or exit its process to be restarted by k8s.

## Context

This problem occurred when I try to update k8s from v1.15 to v1.16 without any Pod evacuations. After the update was completed, typha and calico-node Pods were restarted by new kubelets.

Some calico-node Pods outputted the following logs repeatedly:
```
2019-12-23 06:52:03.624 [ERROR][18432] main.go 96: Failed to connect to Typha. Retrying... error=dial tcp 10.68.51.44:5473: connect: connection refused
2019-12-23 06:52:03.624 [INFO][18432] sync_client.go 169: Starting Typha client
2019-12-23 06:52:03.624 [INFO][18432] sync_client.go 174:  requiringTLS=false
```
typha Pod outputted the following logs only once:
[typha.log](https://gist.github.com/kfyharukz/f231e451721538808248e42612a5a1c0)

## My Environment

It occurred when updating k8s v1.15 to v1.16.
The container image of typha and calico-node was built by the [Dockerfile](https://github.com/cybozu/neco-containers/blob/master/calico/Dockerfile) and calico was deployed with the [manifest](https://github.com/cybozu-go/neco-apps/tree/master/network-policy/base/calico).

## Note

I think reproduction is difficult, however, I saw this situation twice in the same shaped infrastructures. Please provide any additional information if anyone sees the same problem.

**Comment by spikecurtis** [comment]
@kfyharukz what version of Calico are you running?  

I wasn't able to reproduce this on Calico v3.11. What I did was kill the API server, and wait for it to be restarted.  My typha logs dropping connections to the kube-apiserver, but retries and recovers.

**Comment by kfyharukz** [comment]
I used Calico v3.11.1. Is it the same as yours?

**Comment by kfyharukz** [comment]
@spikecurtis I used Calico v3.11.1. Is it the same as yours?

**Comment by spikecurtis** [comment]
@kfyharukz I'm working with 3.11.2.  I'll try later today with a v3.11.1 build

**Comment by spikecurtis** [comment]
@kfyharukz I've tried with 3.11.1 and got the same result, when I killed the API server and recreated it Typha reconnected without a hitch.

The log file you included shows some issues with authorization on some Calico resources, and then also `error=the server is currently unable to handle the request `.  Did the authorization errors go away after you restarted the Typha pod?  Is it possible the Kube API server was just overworked for some time that it couldn't process Typha's requests?  How long did you wait before restarting the Typha pod?

**Comment by kfyharukz** [comment]
> Did the authorization errors go away after you restarted the Typha pod? 

Yes, when I restarted the Typha Pods, it worked well (maybe, about 30 minutes after the kube-apiserver was restarted).
> Did the authorization errors go away after you restarted the Typha pod? Is it possible the Kube API server was just overworked for some time that it couldn't process Typha's requests?

I think the overload situation on the kube-apiserver likely occurred. However, in my understanding, Typha retries to connect to the kube-apiserver, doesn't it?

**Comment by spikecurtis** [comment]
> I think the overload situation on the kube-apiserver likely occurred. However, in my understanding, Typha retries to connect to the kube-apiserver, doesn't it?

Typha retries when it gets an error from the attempt to watch / list the resources, but it the watch or list attempt just hangs, then it will wait. I think those requests will eventually time out, but I'm not sure how long we wait---we just use the default timeouts in the relevant kubernetes client libraries.

How long did you wait before restarting the Typha pod?

**Comment by kfyharukz** [comment]
> How long did you wait before restarting the Typha pod?

Sorry, it's not clear but about a few hours, I think.

**Comment by spikecurtis** [comment]
@kfyharukz I don't suppose you know how to reproduce the problem, do you?

It seems likely that Typha's attempt to resync with the API Server got hung up for some reason, rather than error out (if it had, we would see error logs and Typha _should_ retry the connection).  It would be great to understand why the request hung, but I can't make much progress without a reproduction.

One other angle to think about is liveness/readiness.  You said that during the problematic time, Felix was logging that it was getting connection refused from Typha.  What was Typha's readiness state during that time? Setting ready to false would at least keep Typhas in that state from joining the service that Felix uses.

**Comment by kfyharukz** [comment]
> but I can't make much progress without a reproduction.
I think so too. But, reproduction is difficult also for me because the environments are already stable states.

However, in a few months, we will try to update k8s from 1.16 to 1.17.
If this problem occurs again, I can gather more detailed information.
So, I would close this issue once, and if I can reproduce the problem, I want to reopen it.

Thanks.

**Comment by iuriaranda** [comment]
We're bumping into a very similar issue on EKS. It happens every time we upgrade the control plane of a cluster, when the API servers get recreated.

We've been able to reproduce the issue quite systematically, here's how:

1. Create a new EKS cluster and launch some nodes (k8s version 1.16) (`eksctl create cluster --version 1.16`)
1. Deploy Calico as described in [the AWS documentation ](https://docs.aws.amazon.com/eks/latest/userguide/calico.html), which deploys Calico v3.13.4 (we've also tried with the latest version 3.16 with the same results)
1. Trigger a control plane upgrade to version 1.17
1. Wait until the upgrade is finished
1. Launch a new Pod and watch how it doesn't have network connectivity (you might need to repeat this step as the issue usually doesn't occur until a few minutes after the upgrade finished)

What we have observed is the following:

- all Pods that were running before the upgrade are not affected, they continue to have connectivity after the upgrade. Only new Pods are impacted
- Calico Pods don't show any errors in the logs, they are still connected to typha, but they are not receiving any updates of new Pods being launched, thus they don't update the iptables accordingly.
- after a couple minutes after the upgrade has finished, supposedly when the last of the old API servers is terminated, typha stops receiving watcher updates, but no errors are reported
- if we restart the typha Pod(s), the new typha Pod starts correctly and the issue is immediately resolved
- if we don't restart the typha Pod(s), the issue lasts for about 20 to 30 minutes, after that typha recovers the connectivity with the API server by itself and receives all the pending updates, and new Pods gain connectivity.

We haven't been able to figure out what's the actual cause for the issue, but it seems likely that it's something to do with the reconnection mechanism of typha to the API server. Any ideas?

**Comment by fasaxc** [comment]
I believe this is caused by this issue in kubernetes upstream: https://github.com/kubernetes/kubernetes/issues/87615

**Comment by iuriaranda** [comment]
So if I understand it correctly, the problem is with the `http2` library from Golang, which is used in the k8s library, which in turn is used by both kubelet and typha, right?

It makes sense. Although the strange thing is that we're not seeing the same behaviour on our kubelets, shouldn't they have problems reconnecting to the API as well?

**Comment by fasaxc** [comment]
I think kubelet has a workaround in place

**Comment by iuriaranda** [comment]
Can't we implement a similar workaround here? I'm not that familiar with the project, nor with Go, so I can't really know if it's an easy fix or not. Considering it's quite a high impact issue, I think it's worth investigating.

**Comment by lwr20** [comment]
Likely related to https://github.com/projectcalico/libcalico-go/issues/1267 which is in turn related to https://github.com/kubernetes/kubernetes/pull/95981
