### ISSUE TITLE
Typha watching Nodes in policy-only mode

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/typha#7]
```
2017-06-06 20:27:50.888 [DEBUG][9] syncer.go 522: Incoming Node watch event. Type=MODIFIED
```

I see the above log indicating that Typha is watching Nodes even though Calico is meant to be enforcing policy-only.

Maybe this isn't a big deal when using Typha and we can ignore, but thought I'd bring it up!

**Comment by fasaxc** [comment]
Yeah, that's WAD for now; Typha doesn't load config from the datastore at this time so it can't be sure that the Node watch isn't required.

Note: Typha squashes duplicate HostIP updates that would be caused by unrelated node updates so Felix doesn't actually see the same level of churn that we used to have to deal with, it only sees updates when the Node's IP changes or when nodes are added/removed.
